# Generated by Django 4.1 on 2022-08-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='gif',
            field=models.ManyToManyField(blank=True, to='gifs.gif'),
        ),
    ]
